export const DEMO_SCENES = [
  {
    id: "living",
    nav: "场景一：客厅日常",
    title: "客厅里的日常活动",
    room: "客厅",
    privacy: "安静守护",
    tone: "safe",
    status: "状态平稳",
    summary: "外婆正在客厅活动，系统只关注姿态变化，不主动打扰。",
    phoneTitle: "外婆正在客厅活动",
    phoneBody: "刚刚有正常活动，家里一切平稳。",
    backgroundImage: "/scenes/living-room.jpg",
    conversationScenario: "proactive_check_in",
    autoConversation: false,
  },
  {
    id: "kitchen",
    nav: "场景二：厨房时光",
    title: "厨房里的温暖日常",
    room: "厨房",
    privacy: "本人同意后分享",
    tone: "memory",
    status: "发现温暖时刻",
    summary: "发现外婆正在包包子，先问问她是否愿意把这一刻分享给家人。",
    phoneTitle: "有一段厨房里的好时光",
    phoneBody: "等外婆点头后，再把这份日常发给家人。",
    backgroundImage: "/scenes/kitchen.jpg",
    conversationScenario: "kitchen_share",
    autoConversation: true,
  },
  {
    id: "bathroom",
    nav: "场景三：浴室隐私",
    title: "浴室里的隐私守护",
    room: "浴室",
    privacy: "仅保留姿态",
    tone: "privacy",
    status: "隐私模式已开启",
    summary: "不展示现场画面，只保留必要的姿态变化。",
    phoneTitle: "外婆正在使用浴室",
    phoneBody: "隐私模式已开启，当前活动状态平稳。",
    backgroundImage: "/scenes/bathroom.jpg",
    conversationScenario: null,
    autoConversation: false,
  },
  {
    id: "fall",
    nav: "场景四：夜间守护",
    title: "夜间安全守护",
    room: "深夜客厅",
    privacy: "异常时主动关怀",
    tone: "night",
    status: "静默守护中",
    summary: "夜间持续关注动作变化，发现异常后再主动询问。",
    phoneTitle: "外婆家一切平稳",
    phoneBody: "夜间守护已开启，暂无需要处理的情况。",
    backgroundImage: "/scenes/living-room.jpg",
    conversationScenario: "proactive_check_in",
    autoConversation: true,
  },
];

export const FALL_PHASES = {
  idle: {
    status: "静默守护中",
    message: "系统会持续关注动作变化，发现明显异常后再主动询问。",
  },
  candidate: {
    status: "发现较大的动作变化",
    message: "动作变化有些突然，系统正在继续确认。",
  },
  checking: {
    status: "正在确认是否安全",
    message: "奶奶，刚才的动作有点突然，您还好吗？",
  },
  emergency: {
    status: "已通知家人查看",
    message: "一直没有听到回应，已按预授权通知家人查看现场。",
  },
  contacting: {
    status: "正在联系身边的人",
    message: "家人已经收到提醒，系统正在联系附近的王阿姨。",
  },
  resolved: {
    status: "附近联系人已响应",
    message: "王阿姨已经出发，家人会继续关注现场情况。",
  },
};
