export const DEMO_SCENES = [
  {
    id: "living",
    nav: "场景一：客厅行走",
    title: "正常客厅行走",
    room: "客厅",
    privacy: "骨架守护",
    tone: "safe",
    status: "一切正常",
    summary: "仅同步姿态节点，不展示可识别真人画面",
    phoneTitle: "外婆正在客厅活动",
    phoneBody: "步态平稳，当前无需打扰",
    conversationScenario: "proactive_check_in",
    autoConversation: false,
  },
  {
    id: "kitchen",
    nav: "场景二：厨房包包子",
    title: "厨房包包子",
    room: "厨房",
    privacy: "生活场景",
    tone: "memory",
    status: "值得记录",
    summary: "识别到包包子场景，等待本人确认后分享",
    phoneTitle: "发现值得分享的瞬间",
    phoneBody: "奶奶正在包包子，等待她确认",
    conversationScenario: "kitchen_share",
    autoConversation: true,
  },
  {
    id: "bathroom",
    nav: "场景三：浴室洗澡",
    title: "浴室隐私保护",
    room: "浴室",
    privacy: "最高隐私",
    tone: "privacy",
    status: "隐私保护中",
    summary: "真人画面与音频已关闭，仅保留姿态节点",
    phoneTitle: "隐私保护已开启",
    phoneBody: "外婆正在洗澡，当前活动正常",
    conversationScenario: null,
    autoConversation: false,
  },
  {
    id: "fall",
    nav: "场景四：深夜跌倒",
    title: "深夜安全守护",
    room: "深夜客厅",
    privacy: "骨架守护",
    tone: "night",
    status: "夜间守护中",
    summary: "保持骨架隐私模式，等待现场动作",
    phoneTitle: "外婆家一切正常",
    phoneBody: "深夜守护已开启",
    conversationScenario: "proactive_check_in",
    autoConversation: true,
  },
];

export const FALL_PHASES = {
  idle: {
    status: "夜间守护中",
    message: "请先在镜头前准备跌倒姿态，再启动演示流程",
  },
  candidate: {
    status: "检测到异常动作候选",
    message: "A：身体重心快速下降，正在持续观察",
  },
  checking: {
    status: "正在确认安全",
    message: "MiMo：奶奶，检测到您可能摔倒了，您还好吗？",
  },
  emergency: {
    status: "紧急查看已开启",
    message: "未收到回应，已按预授权临时开放现场画面",
  },
  contacting: {
    status: "正在联系紧急联系人",
    message: "已通知孙女，并正在呼叫附近联系人王阿姨",
  },
  resolved: {
    status: "联系人已响应",
    message: "王阿姨已确认前往，紧急画面将在确认安全后关闭",
  },
};
