export const FAMILY_TIMELINE_MOCK_START_DATE = "2026-08-04";
export const FAMILY_TIMELINE_MOCK_END_DATE = "2026-08-11";

function timestamp(day, hour, minute) {
  return new Date(2026, 7, day, hour, minute, 0, 0).getTime();
}

function mockAssessment({
  day,
  hour,
  minute,
  title,
  basis,
  suggestedAction,
  progress,
  statusLabel = "安静观察",
  tone = "neutral",
  uncertainty = "medium",
  sceneId = "living",
}) {
  const dateKey = `2026-08-${String(day).padStart(2, "0")}`;
  return Object.freeze({
    id: `mock:${dateKey}:${String(hour).padStart(2, "0")}${String(minute).padStart(2, "0")}`,
    kind: "assessment",
    label: "Mock 关怀判断",
    title,
    detail: basis,
    timestampMs: timestamp(day, hour, minute),
    dateKey,
    tone,
    statusLabel,
    suggestedAction,
    progress,
    assessmentSource: "mock",
    uncertainty,
    visualContext: null,
    source: "mock_fixture",
    stateRevision: null,
    sceneId,
    sceneLabel: sceneId === "kitchen" ? "厨房时光" : "客厅日常",
    captureStatus: null,
    captureLabel: null,
    runtimeStatus: null,
    runtimeLabel: null,
    priority: 90,
    batchOrder: 0,
  });
}

export const FAMILY_TIMELINE_MOCK_EVENTS = Object.freeze([
  mockAssessment({
    day: 4,
    hour: 8,
    minute: 6,
    title: "今天起身稍晚，但随后活动连续",
    basis: "Mock 姿态窗口显示起身时间比近期习惯晚约 18 分钟，之后出现连续站立与走动。",
    suggestedAction: "暂时无需打扰，继续安静观察",
    progress: "没有待处理事项",
  }),
  mockAssessment({
    day: 4,
    hour: 18,
    minute: 42,
    title: "傍晚有多次起身走动，活动节奏较平稳",
    basis: "Mock 姿态序列记录到多次坐立转换，没有持续静止信号。",
    suggestedAction: "维持日常关怀即可",
    progress: "持续观察中",
    uncertainty: "low",
  }),
  mockAssessment({
    day: 5,
    hour: 11,
    minute: 58,
    title: "午间静坐时间比近期习惯更长，已经发起问候",
    basis: "Mock 行为窗口显示连续坐姿时间超过近期同一时段的个人基线。",
    suggestedAction: "等待本人回应，暂不把原因定性",
    progress: "问候已发出",
    statusLabel: "等待回应",
    tone: "warning",
  }),
  mockAssessment({
    day: 5,
    hour: 12,
    minute: 5,
    title: "本人回应正在看电视，本次关怀已经结束",
    basis: "Mock 回应已进入关怀闭环，没有留下需要家属处理的事项。",
    suggestedAction: "无需继续操作",
    progress: "本人已回应",
    statusLabel: "已经处理",
    tone: "success",
    uncertainty: "low",
  }),
  mockAssessment({
    day: 6,
    hour: 9,
    minute: 20,
    title: "上午活动分布与近期习惯接近",
    basis: "Mock 行为窗口中的站立、坐姿和短时走动比例没有明显偏离个人基线。",
    suggestedAction: "继续保持安静守护",
    progress: "没有待处理事项",
    uncertainty: "low",
  }),
  mockAssessment({
    day: 6,
    hour: 17,
    minute: 50,
    title: "厨房出现持续活动，可能正在准备晚餐",
    basis: "Mock 厨房场景中出现连续站立、弯腰和手部活动；仅能判断为厨房活动。",
    suggestedAction: "无需打扰，保留为一段生活记忆",
    progress: "持续观察中",
    sceneId: "kitchen",
  }),
  mockAssessment({
    day: 7,
    hour: 7,
    minute: 35,
    title: "晨间从躺卧到站立的转换连续",
    basis: "Mock 姿态序列显示转换过程连贯，暂未出现需要行动的信号。",
    suggestedAction: "继续观察晨间活动",
    progress: "没有待处理事项",
    uncertainty: "low",
  }),
  mockAssessment({
    day: 7,
    hour: 15,
    minute: 10,
    title: "下午活动量低于近期基线，建议稍后问候",
    basis: "Mock 行为窗口显示同一时段的起身次数减少，但原因尚不能确认。",
    suggestedAction: "稍后发起一次轻量问候",
    progress: "等待合适时机",
    statusLabel: "值得留意",
    tone: "warning",
    uncertainty: "high",
  }),
  mockAssessment({
    day: 8,
    hour: 13,
    minute: 5,
    title: "午后持续坐着较长时间，已经轻声问候",
    basis: "Mock 姿态窗口记录到约 45 分钟连续坐姿，触发非紧急关怀。",
    suggestedAction: "等待本人回应",
    progress: "问候已发出",
    statusLabel: "等待回应",
    tone: "warning",
  }),
  mockAssessment({
    day: 8,
    hour: 13,
    minute: 12,
    title: "本人回应正在听广播，状态已经确认",
    basis: "Mock 回应明确说明当前活动，本次问候无需升级给家属。",
    suggestedAction: "无需继续操作",
    progress: "本人已回应",
    statusLabel: "已经处理",
    tone: "success",
    uncertainty: "low",
  }),
  mockAssessment({
    day: 9,
    hour: 8,
    minute: 22,
    title: "晨间活动连续，起身后有多次短距离走动",
    basis: "Mock 姿态序列显示站立和走动片段连续，没有持续静止信号。",
    suggestedAction: "维持日常关怀即可",
    progress: "没有待处理事项",
    uncertainty: "low",
  }),
  mockAssessment({
    day: 9,
    hour: 21,
    minute: 40,
    title: "晚间持续躺卧，可能已经开始休息",
    basis: "Mock 姿态窗口只能确认持续躺卧，不能据此断言已经睡着。",
    suggestedAction: "暂不打扰；若长时间无变化再轻量确认",
    progress: "安静观察中",
    uncertainty: "high",
  }),
  mockAssessment({
    day: 10,
    hour: 10,
    minute: 30,
    title: "上午活动节奏规律，未触发主动问候",
    basis: "Mock 行为窗口与个人近期同一时段接近，没有明显偏离信号。",
    suggestedAction: "继续保持安静守护",
    progress: "没有待处理事项",
    uncertainty: "low",
  }),
  mockAssessment({
    day: 10,
    hour: 18,
    minute: 5,
    title: "厨房出现一段持续活动，可能在准备晚餐",
    basis: "Mock 厨房上下文中出现连续站立和弯腰；系统没有进一步判断具体菜品或进食结果。",
    suggestedAction: "无需主动打扰",
    progress: "记录为生活片段",
    sceneId: "kitchen",
    uncertainty: "high",
  }),
  mockAssessment({
    day: 11,
    hour: 9,
    minute: 5,
    title: "今天起身比近一周平均稍早，活动衔接自然",
    basis: "Mock 行为记忆显示起身时间提前约 12 分钟，后续姿态转换保持连续。",
    suggestedAction: "继续观察日常节奏",
    progress: "没有待处理事项",
  }),
  mockAssessment({
    day: 11,
    hour: 20,
    minute: 30,
    title: "这一周的主动问候都获得了回应",
    basis: "Mock 周期汇总显示两次轻量问候均已闭环，目前没有遗留的家庭行动项。",
    suggestedAction: "保持当前关怀频率",
    progress: "本周事项已闭环",
    statusLabel: "一周回顾",
    tone: "success",
    uncertainty: "low",
  }),
]);

export function isFamilyTimelineMockDate(dateKey) {
  return dateKey >= FAMILY_TIMELINE_MOCK_START_DATE
    && dateKey <= FAMILY_TIMELINE_MOCK_END_DATE;
}
